blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/salimc93/exiqus-oss/discussions
    about: Ask questions and discuss ideas in Discussions rather than issues.
