"""Add status field to analysis tables

Revision ID: 99a0832c96a9
Revises: 7b42c9bc6ae9
Create Date: 2025-10-25 23:46:01.433045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99a0832c96a9"
down_revision: Union[str, None] = "7b42c9bc6ae9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)

    # Create enum type for PostgreSQL (will be no-op for SQLite)
    analysisstatus = sa.Enum(
        "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="analysisstatus"
    )
    analysisstatus.create(bind, checkfirst=True)

    # Add status column to analysis_results if it doesn't exist
    columns = [c["name"] for c in inspector.get_columns("analysis_results")]
    if "status" not in columns:
        op.add_column(
            "analysis_results",
            sa.Column(
                "status", analysisstatus, nullable=False, server_default="COMPLETED"
            ),
        )
    else:
        # Column exists but might be VARCHAR, need to update existing rows to use enum values
        bind.execute(
            sa.text(
                "UPDATE analysis_results SET status = 'COMPLETED' WHERE status NOT IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')"
            )
        )

    # Create index if it doesn't exist
    indexes = [i["name"] for i in inspector.get_indexes("analysis_results")]
    if "ix_analysis_results_status" not in indexes:
        op.create_index(
            op.f("ix_analysis_results_status"),
            "analysis_results",
            ["status"],
            unique=False,
        )

    # SQLite doesn't support ALTER COLUMN TYPE - skip for local dev, will work in PostgreSQL production
    # op.alter_column('pr_analysis_records', 'analysis_id', existing_type=sa.TEXT(), type_=sa.String(length=50), existing_nullable=True)

    # Add status column to pr_analysis_results if it doesn't exist
    columns = [c["name"] for c in inspector.get_columns("pr_analysis_results")]
    if "status" not in columns:
        op.add_column(
            "pr_analysis_results",
            sa.Column(
                "status", analysisstatus, nullable=False, server_default="COMPLETED"
            ),
        )
    else:
        # Column exists but might be VARCHAR, need to update existing rows to use enum values
        bind.execute(
            sa.text(
                "UPDATE pr_analysis_results SET status = 'COMPLETED' WHERE status NOT IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')"
            )
        )

    # SQLite doesn't support ALTER COLUMN TYPE - skip for local dev, will work in PostgreSQL production
    # op.alter_column('pr_analysis_results', 'total_time_seconds', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)

    # Create indexes if they don't exist
    indexes = [i["name"] for i in inspector.get_indexes("pr_analysis_results")]
    if "ix_pr_analysis_results_role" not in indexes:
        op.create_index(
            op.f("ix_pr_analysis_results_role"),
            "pr_analysis_results",
            ["role"],
            unique=False,
        )
    if "ix_pr_analysis_results_status" not in indexes:
        op.create_index(
            op.f("ix_pr_analysis_results_status"),
            "pr_analysis_results",
            ["status"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    op.drop_index(
        op.f("ix_pr_analysis_results_status"), table_name="pr_analysis_results"
    )
    op.drop_index(op.f("ix_pr_analysis_results_role"), table_name="pr_analysis_results")
    op.alter_column(
        "pr_analysis_results",
        "total_time_seconds",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.drop_column("pr_analysis_results", "status")
    op.alter_column(
        "pr_analysis_records",
        "analysis_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_analysis_results_status"), table_name="analysis_results")
    op.drop_column("analysis_results", "status")

    # Drop enum type for PostgreSQL (will be no-op for SQLite)
    analysisstatus = sa.Enum(
        "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="analysisstatus"
    )
    analysisstatus.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
