"""add_repository_deep_dive_tracking

Revision ID: cfae7ff43be3
Revises: 30e44396fcfd
Create Date: 2025-10-23 11:33:16.040265

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfae7ff43be3"
down_revision: Union[str, None] = "30e44396fcfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create repository_deep_dives table
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if "repository_deep_dives" not in existing_tables:
        op.create_table(
            "repository_deep_dives",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=50), nullable=False),
            sa.Column("repository_name", sa.String(length=255), nullable=False),
            sa.Column("billing_period", sa.String(length=7), nullable=False),
            sa.Column("analysis_id", sa.String(length=50), nullable=True),
            sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["analysis_id"],
                ["analysis_results.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.user_id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_repository_deep_dives_user_id"),
            "repository_deep_dives",
            ["user_id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_repository_deep_dives_repository_name"),
            "repository_deep_dives",
            ["repository_name"],
            unique=False,
        )
        op.create_index(
            op.f("ix_repository_deep_dives_billing_period"),
            "repository_deep_dives",
            ["billing_period"],
            unique=False,
        )
        op.create_index(
            op.f("ix_repository_deep_dives_created_at"),
            "repository_deep_dives",
            ["created_at"],
            unique=False,
        )
        print("✅ Created repository_deep_dives table")
    else:
        print("⏭️  repository_deep_dives table already exists")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pr_analysis_results_role"), table_name="pr_analysis_results")
    op.alter_column(
        "pr_analysis_results",
        "total_time_seconds",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "pr_analysis_records", type_="foreignkey")
    op.drop_index(
        op.f("ix_pr_analysis_records_analysis_id"), table_name="pr_analysis_records"
    )
    op.create_index(
        op.f("idx_pr_analysis_records_analysis_id"),
        "pr_analysis_records",
        ["analysis_id"],
        unique=False,
    )
    op.alter_column(
        "pr_analysis_records",
        "analysis_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "pr_analysis_records",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(
        op.f("idx_portfolio_user_id"), "portfolio_analyses", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_portfolio_github_username"),
        "portfolio_analyses",
        ["github_username"],
        unique=False,
    )
    op.create_index(
        op.f("idx_portfolio_created_at"),
        "portfolio_analyses",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_contexts_locked_by_user_id"),
        "candidate_contexts",
        ["locked_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_candidate_user_id"),
        "candidate_assessments",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_candidate_github_username"),
        "candidate_assessments",
        ["github_username"],
        unique=False,
    )
    op.create_index(
        op.f("idx_candidate_created_at"),
        "candidate_assessments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_candidate_billing_period"),
        "candidate_assessments",
        ["billing_period"],
        unique=False,
    )
    op.add_column(
        "analysis_results", sa.Column("overall_score", sa.FLOAT(), nullable=True)
    )
    op.add_column(
        "analysis_results",
        sa.Column("recommendation", sa.VARCHAR(length=50), nullable=True),
    )
    op.add_column(
        "analysis_results", sa.Column("confidence_score", sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
