"""add_progress_tracking_fields

Revision ID: 4e1830c00cf2
Revises: a228480bb04d
Create Date: 2025-10-26 01:50:17.888365

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e1830c00cf2"
down_revision: Union[str, None] = "a228480bb04d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first if it doesn't exist (PostgreSQL idempotent)
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE analysisstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """
    )

    # Convert batch_analyses.status column with USING clause for PostgreSQL
    op.execute(
        """
        ALTER TABLE batch_analyses
        ALTER COLUMN status TYPE analysisstatus
        USING UPPER(status)::analysisstatus
    """
    )

    op.create_index(
        op.f("ix_batch_analyses_status"), "batch_analyses", ["status"], unique=False
    )
    op.add_column(
        "portfolio_analyses",
        sa.Column("progress_stage", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "portfolio_analyses", sa.Column("progress_percent", sa.Integer(), nullable=True)
    )
    op.add_column(
        "portfolio_analyses",
        sa.Column("progress_message", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "pr_analysis_records",
        "analysis_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.add_column(
        "pr_analysis_results",
        sa.Column("progress_stage", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "pr_analysis_results",
        sa.Column("progress_percent", sa.Integer(), nullable=True),
    )
    op.add_column(
        "pr_analysis_results",
        sa.Column("progress_message", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "pr_analysis_results",
        "total_time_seconds",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pr_analysis_results",
        "total_time_seconds",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.drop_column("pr_analysis_results", "progress_message")
    op.drop_column("pr_analysis_results", "progress_percent")
    op.drop_column("pr_analysis_results", "progress_stage")
    op.alter_column(
        "pr_analysis_records",
        "analysis_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("portfolio_analyses", "progress_message")
    op.drop_column("portfolio_analyses", "progress_percent")
    op.drop_column("portfolio_analyses", "progress_stage")
    op.drop_index(op.f("ix_batch_analyses_status"), table_name="batch_analyses")

    # Convert batch_analyses.status back to VARCHAR
    op.execute(
        """
        ALTER TABLE batch_analyses
        ALTER COLUMN status TYPE VARCHAR(20)
        USING status::text
    """
    )

    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS analysisstatus")
    # ### end Alembic commands ###
