"""add_status_to_portfolio_analyses

Revision ID: a228480bb04d
Revises: 99a0832c96a9
Create Date: 2025-10-26 00:21:46.149964

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a228480bb04d"
down_revision: Union[str, None] = "99a0832c96a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column with server default for existing rows (SQLite compatible)
    op.add_column(
        "portfolio_analyses",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="analysisstatus"
            ),
            nullable=False,
            server_default="COMPLETED",
        ),
    )
    op.create_index(
        op.f("ix_portfolio_analyses_status"),
        "portfolio_analyses",
        ["status"],
        unique=False,
    )

    # SQLite doesn't support ALTER COLUMN TYPE - skip for local dev, will work in PostgreSQL production
    # op.alter_column('pr_analysis_records', 'analysis_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # op.alter_column('pr_analysis_results', 'total_time_seconds',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pr_analysis_results",
        "total_time_seconds",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "pr_analysis_records",
        "analysis_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_portfolio_analyses_status"), table_name="portfolio_analyses")
    op.drop_column("portfolio_analyses", "status")
    # ### end Alembic commands ###
