"""Tests for PortfolioAnalyzer orchestration.

Following the Orchestration Principle:
- Test the workflow coordination, not implementation details
- Verify components are called with correct arguments
- Verify results are assembled correctly
- NO SCORES OR RATINGS - evidence-based only
"""

from datetime import datetime, timezone
from unittest.mock import patch

import pytest

from github_analyzer.data.portfolio_analyzer import PortfolioAnalyzer
from github_analyzer.data.portfolio_models import (
    PortfolioFetchResult,
    RepoData,
)


@pytest.fixture
def mock_github_token():
    """Mock GitHub token."""
    return "ghp_test_token_123"


@pytest.fixture
def mock_anthropic_key():
    """Mock Anthropic API key."""
    return "sk-ant-test-key-123"


@pytest.fixture
def sample_repos():
    """Sample repos for testing."""
    return [
        RepoData(
            name="test-repo-1",
            full_name="user/test-repo-1",
            url="https://github.com/user/test-repo-1",
            owner="user",
            created_at=datetime(2023, 1, 1, tzinfo=timezone.utc),
            updated_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
            pushed_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
            stars=10,
            forks=2,
            watchers=5,
            is_fork=False,
            is_archived=False,
            is_private=False,
            primary_language="Python",
            languages={"Python": 10000, "JavaScript": 2000},
            total_commits=50,
            topics=["web", "api"],
            description="Test repository",
            size_kb=500,
            open_issues=3,
            has_wiki=True,
            has_pages=False,
        ),
        RepoData(
            name="test-repo-2",
            full_name="user/test-repo-2",
            url="https://github.com/user/test-repo-2",
            owner="user",
            created_at=datetime(2023, 6, 1, tzinfo=timezone.utc),
            updated_at=datetime(2024, 6, 1, tzinfo=timezone.utc),
            pushed_at=datetime(2024, 6, 1, tzinfo=timezone.utc),
            stars=25,
            forks=5,
            watchers=10,
            is_fork=False,
            is_archived=False,
            is_private=False,
            primary_language="TypeScript",
            languages={"TypeScript": 15000, "CSS": 3000},
            total_commits=75,
            topics=["react", "frontend"],
            description="Frontend application",
            size_kb=800,
            open_issues=1,
            has_wiki=False,
            has_pages=True,
        ),
    ]


@pytest.fixture
def mock_fetch_result(sample_repos):
    """Mock fetch result."""
    return PortfolioFetchResult(
        repos=sample_repos,
        username="testuser",
        total_public_repos=2,
        repos_fetched=2,
        repos_skipped=0,
        skip_reasons={},
        skipped_repos=[],
        api_calls_used=1,
        fetch_time_seconds=1.5,
        all_repos_dates=["2024-01-01T00:00:00Z", "2023-01-01T00:00:00Z"],
    )


@pytest.fixture
def mock_evidence():
    """Mock evidence extracted from repos."""
    return {
        "public_repos_timeline": [
            "2023: test-repo-1 (Python)",
            "2023: test-repo-2 (TypeScript)",
        ],
        "technology_adoption_timeline": [
            "Python: First observed in public repos on 2023-01-01",
            "TypeScript: First observed in public repos on 2023-06-01",
        ],
        "public_work_quality_indicators": [],
        "timeline_gaps": [],
        "cross_technology_evidence": [
            "Technologies observed in public repos: CSS, JavaScript, Python, TypeScript"
        ],
        "portfolio_evolution_periods": [],
        "substantial_repos_structured": [],
        "technology_evolution_evidence": [],
        "quality_progression_evidence": [],
        "cross_repo_patterns": [],
        "aggregated_technologies": {
            "Python": 1,
            "TypeScript": 1,
            "JavaScript": 1,
            "CSS": 1,
        },
        "aggregated_quality_indicators": {},
        "repo_substance_indicators": [],
    }


@pytest.fixture
def mock_insights_result():
    """Mock insights generated by AI."""
    return {
        "success": True,
        "model_used": "claude-3-5-sonnet-20241022",
        "total_tokens": 1500,
        "cost": 0.015,
        "insights": {
            "executive_summary": "Test portfolio summary",
            "data_limitations_warning": "PUBLIC REPOSITORIES ONLY",
            "key_observations": [
                "Uses Python and TypeScript",
                "Active in web development",
            ],
            "public_portfolio_evolution": [],
            "evidence_patterns": [],
            "interview_questions": [],
            "positive_indicators": [],
            "areas_to_explore": [],
            "recommendations": [],
            "quality_indicators": [],
            "confidence_explanation": "Based on 2 public repos",
        },
    }


class TestPortfolioAnalyzer:
    """Test suite for PortfolioAnalyzer orchestration."""

    def test_analyzer_initialization(self, mock_github_token, mock_anthropic_key):
        """Test that analyzer initializes all components correctly."""
        with (
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioFetcher"
            ) as mock_fetcher_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioEvidenceExtractor"
            ) as mock_extractor_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioInsightsGenerator"
            ) as mock_generator_class,
        ):
            analyzer = PortfolioAnalyzer(mock_github_token, mock_anthropic_key)

            # Verify fetcher was initialized with GitHub token
            mock_fetcher_class.assert_called_once_with(mock_github_token)

            # Verify evidence extractor was initialized
            mock_extractor_class.assert_called_once_with()

            # Verify insights generator was initialized with Anthropic key
            mock_generator_class.assert_called_once_with(mock_anthropic_key)

            # Verify analyzer has all components
            assert analyzer.fetcher == mock_fetcher_class.return_value
            assert analyzer.evidence_extractor == mock_extractor_class.return_value
            assert analyzer.insights_generator == mock_generator_class.return_value

    def test_analyze_portfolio_orchestration(
        self,
        mock_github_token,
        mock_anthropic_key,
        mock_fetch_result,
        mock_evidence,
        mock_insights_result,
    ):
        """Test that analyze_portfolio orchestrates all components correctly."""
        with (
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioFetcher"
            ) as mock_fetcher_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioEvidenceExtractor"
            ) as mock_extractor_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioInsightsGenerator"
            ) as mock_generator_class,
        ):
            # Setup mocks
            mock_fetcher = mock_fetcher_class.return_value
            mock_fetcher.fetch_user_portfolio.return_value = mock_fetch_result

            mock_extractor = mock_extractor_class.return_value
            mock_extractor.extract_all_evidence.return_value = mock_evidence

            mock_generator = mock_generator_class.return_value
            mock_generator.generate_insights.return_value = mock_insights_result

            # Create analyzer and run analysis
            analyzer = PortfolioAnalyzer(mock_github_token, mock_anthropic_key)
            result = analyzer.analyze_portfolio(
                username="testuser",
                context="enterprise",
                tier="professional",
                max_repos=100,
                role="senior",
            )

            # Verify fetcher was called correctly
            mock_fetcher.fetch_user_portfolio.assert_called_once_with("testuser", 100)

            # Verify evidence extractor was called with repos and username
            mock_extractor.extract_all_evidence.assert_called_once()
            call_args = mock_extractor.extract_all_evidence.call_args
            assert call_args[0][0] == mock_fetch_result.repos  # repos
            assert call_args[0][1] == "testuser"  # username

            # Verify insights generator was called with correct arguments
            mock_generator.generate_insights.assert_called_once()
            insights_call = mock_generator.generate_insights.call_args[1]
            assert insights_call["username"] == "testuser"
            assert insights_call["evidence"] == mock_evidence
            assert insights_call["repos"] == mock_fetch_result.repos
            assert insights_call["context"] == "enterprise"
            assert insights_call["tier"] == "professional"
            assert insights_call["role"] == "senior"

            # Verify top-level result structure
            assert result["success"] is True
            assert result["username"] == "testuser"
            assert result["context"] == "enterprise"
            assert result["model_used"] == "claude-3-5-sonnet-20241022"

            # Verify nested analysis result
            analysis_result = result["result"]
            assert analysis_result["summary"] == "Test portfolio summary"
            assert analysis_result["limitations"] == "PUBLIC REPOSITORIES ONLY"

            # Verify metadata was passed to insights generator and updated
            metadata = insights_call["metadata"]
            assert metadata.total_public_repos == 2
            assert metadata.repos_analyzed == 2

            # Verify metadata was updated with AI token usage and cost
            result_metadata = result["metadata"]
            assert result_metadata.tokens == 1500  # Updated after AI call
            assert result_metadata.cost == 0.015  # Updated after AI call

    def test_analyze_portfolio_with_failed_insights(
        self,
        mock_github_token,
        mock_anthropic_key,
        mock_fetch_result,
        mock_evidence,
    ):
        """Test that analyzer handles AI insights failure gracefully."""
        with (
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioFetcher"
            ) as mock_fetcher_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioEvidenceExtractor"
            ) as mock_extractor_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioInsightsGenerator"
            ) as mock_generator_class,
        ):
            # Setup mocks with failed insights
            mock_fetcher = mock_fetcher_class.return_value
            mock_fetcher.fetch_user_portfolio.return_value = mock_fetch_result

            mock_extractor = mock_extractor_class.return_value
            mock_extractor.extract_all_evidence.return_value = mock_evidence

            mock_generator = mock_generator_class.return_value
            mock_generator.generate_insights.return_value = {
                "success": False,
                "error": "AI service unavailable",
                "insights": {},
            }

            # Create analyzer and run analysis
            analyzer = PortfolioAnalyzer(mock_github_token, mock_anthropic_key)
            result = analyzer.analyze_portfolio(
                username="testuser",
                context="startup",
                tier="free",
            )

            # Verify analysis completed despite AI failure
            assert result["success"] is True  # Analysis still succeeds
            assert result["username"] == "testuser"
            assert result["context"] == "startup"

            # Verify nested result has fallback values when AI fails
            analysis_result = result["result"]
            assert "testuser" in analysis_result["summary"]
            assert "PUBLIC REPOSITORIES ONLY" in analysis_result["limitations"]

    def test_analyze_portfolio_no_scores_in_result(
        self,
        mock_github_token,
        mock_anthropic_key,
        mock_fetch_result,
        mock_evidence,
        mock_insights_result,
    ):
        """CRITICAL: Verify NO scores or ratings in analysis result."""
        with (
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioFetcher"
            ) as mock_fetcher_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioEvidenceExtractor"
            ) as mock_extractor_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioInsightsGenerator"
            ) as mock_generator_class,
        ):
            # Setup mocks
            mock_fetcher = mock_fetcher_class.return_value
            mock_fetcher.fetch_user_portfolio.return_value = mock_fetch_result

            mock_extractor = mock_extractor_class.return_value
            mock_extractor.extract_all_evidence.return_value = mock_evidence

            mock_generator = mock_generator_class.return_value
            mock_generator.generate_insights.return_value = mock_insights_result

            # Run analysis
            analyzer = PortfolioAnalyzer(mock_github_token, mock_anthropic_key)
            result = analyzer.analyze_portfolio(username="testuser")

            # CRITICAL: Verify NO forbidden patterns
            result_str = str(result).lower()
            assert "score" not in result_str, "Found forbidden 'score' in result"
            assert "rating" not in result_str, "Found forbidden 'rating' in result"
            assert "grade" not in result_str, "Found forbidden 'grade' in result"
            assert "rank" not in result_str, "Found forbidden 'rank' in result"

    def test_analyze_portfolio_metadata_calculation(
        self,
        mock_github_token,
        mock_anthropic_key,
        mock_fetch_result,
        mock_evidence,
        mock_insights_result,
    ):
        """Test that metadata is calculated correctly from fetch result."""
        with (
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioFetcher"
            ) as mock_fetcher_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioEvidenceExtractor"
            ) as mock_extractor_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioInsightsGenerator"
            ) as mock_generator_class,
        ):
            # Setup mocks
            mock_fetcher = mock_fetcher_class.return_value
            mock_fetcher.fetch_user_portfolio.return_value = mock_fetch_result

            mock_extractor = mock_extractor_class.return_value
            mock_extractor.extract_all_evidence.return_value = mock_evidence

            mock_generator = mock_generator_class.return_value
            mock_generator.generate_insights.return_value = mock_insights_result

            # Run analysis
            analyzer = PortfolioAnalyzer(mock_github_token, mock_anthropic_key)
            analyzer.analyze_portfolio(username="testuser")

            # Verify metadata was correctly built from fetch result
            insights_call = mock_generator.generate_insights.call_args[1]
            metadata = insights_call["metadata"]

            assert metadata.total_public_repos == mock_fetch_result.total_public_repos
            assert metadata.repos_analyzed == mock_fetch_result.repos_fetched
            assert metadata.repos_skipped == mock_fetch_result.repos_skipped
            assert len(metadata.analyzed_repos) == len(mock_fetch_result.repos)

            # Verify oldest/newest repo dates were calculated
            assert metadata.oldest_repo  # Should be set
            assert metadata.newest_repo  # Should be set

            # Verify tokens and cost updated after AI call
            assert metadata.tokens == mock_insights_result["total_tokens"]
            assert metadata.cost == mock_insights_result["cost"]

    def test_analyze_portfolio_empty_repos(
        self,
        mock_github_token,
        mock_anthropic_key,
        mock_evidence,
        mock_insights_result,
    ):
        """Test analyze_portfolio handles empty repos gracefully."""
        empty_fetch_result = PortfolioFetchResult(
            repos=[],
            username="emptyuser",
            total_public_repos=0,
            repos_fetched=0,
            repos_skipped=0,
            skip_reasons={},
            skipped_repos=[],
            api_calls_used=1,
            fetch_time_seconds=0.5,
            all_repos_dates=[],
        )

        with (
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioFetcher"
            ) as mock_fetcher_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioEvidenceExtractor"
            ) as mock_extractor_class,
            patch(
                "github_analyzer.data.portfolio_analyzer.PortfolioInsightsGenerator"
            ) as mock_generator_class,
        ):
            # Setup mocks
            mock_fetcher = mock_fetcher_class.return_value
            mock_fetcher.fetch_user_portfolio.return_value = empty_fetch_result

            mock_extractor = mock_extractor_class.return_value
            mock_extractor.extract_all_evidence.return_value = mock_evidence

            mock_generator = mock_generator_class.return_value
            mock_generator.generate_insights.return_value = mock_insights_result

            # Run analysis
            analyzer = PortfolioAnalyzer(mock_github_token, mock_anthropic_key)
            result = analyzer.analyze_portfolio(username="emptyuser")

            # Verify analysis completes with empty repos
            assert result["username"] == "emptyuser"

            # Verify metadata reflects empty portfolio
            insights_call = mock_generator.generate_insights.call_args[1]
            metadata = insights_call["metadata"]
            assert metadata.total_public_repos == 0
            assert metadata.repos_analyzed == 0
            assert metadata.oldest_repo == ""  # Empty string for no repos
            assert metadata.newest_repo == ""  # Empty string for no repos
