"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.
"""

# ... standard settings
SECRET_KEY = "django-insecure-abc123"  # WARNING: keep secret in production!
DEBUG = True
