"""
Unit tests for Areas to Explore generation.

Tests the doctrinally pure approach where areas_to_explore
are generated by the AI based on repository characteristics.
"""

from unittest.mock import Mock, patch

import pytest

from src.github_analyzer.core.evidence.repository_characteristics import (
    generate_repository_characteristics,
)
from src.github_analyzer.core.report_generator import ReportGenerator
from src.github_analyzer.data.models import FileInfo, RepositoryData


class TestAreasToExplore:
    """Test suite for Areas to Explore functionality."""

    def test_repository_characteristics_generation(self):
        """Test that repository characteristics are generated correctly."""
        # Create mock repository data
        repo_data = Mock(spec=RepositoryData)
        repo_data.name = "facebook/react"
        repo_data.size = 150000  # 150MB
        repo_data.languages = {
            "JavaScript": 5000000,
            "TypeScript": 2000000,
            "HTML": 100000,
            "CSS": 50000,
        }
        # Mix of files with different depths to ensure some are in the first 200
        repo_data.file_structure = []
        # First 100 files with deep paths
        for i in range(100):
            repo_data.file_structure.append(
                Mock(
                    spec=FileInfo,
                    path=f"src/core/components/deep/nested/path/file{i}.js",
                )
            )
        # Next 900 files with shallow paths
        for i in range(900):
            repo_data.file_structure.append(Mock(spec=FileInfo, path=f"src/file{i}.js"))
        repo_data.metrics = Mock(
            total_commits=50000,
            unique_contributors=100,
            total_files=1500,
        )
        repo_data.recent_commits = (
            [Mock(message=f"refactor: clean up component {i}") for i in range(5)]
            + [Mock(message=f"fix: resolve issue #{i}") for i in range(10)]
            + [Mock(message=f"feat: add new feature {i}") for i in range(5)]
        )
        repo_data.has_ci_config = True
        repo_data.has_readme = True
        repo_data.has_license = True

        # Generate characteristics
        characteristics = generate_repository_characteristics(repo_data)

        # Verify characteristics
        assert characteristics["total_file_count"] == 1000
        assert characteristics["max_folder_depth"] >= 6
        assert characteristics["language_count"] == 4
        assert characteristics["primary_language"] == "JavaScript"
        assert characteristics["has_javascript_and_typescript"] is True
        assert characteristics["typescript_percentage"] > 20
        assert characteristics["unique_contributors"] == 100
        assert characteristics["refactoring_commit_count"] == 5
        assert characteristics["is_monorepo"] is True
        assert (
            characteristics["is_library"] is False
        )  # "react" doesn't contain lib/sdk/framework
        assert characteristics["has_ci"] is True

    def test_characteristics_with_minimal_repo(self):
        """Test characteristics generation with minimal repository."""
        # Create minimal repository
        repo_data = Mock(spec=RepositoryData)
        repo_data.name = "simple-script"
        repo_data.size = 10
        repo_data.languages = {"Python": 1000}
        repo_data.file_structure = [
            Mock(spec=FileInfo, path="script.py"),
            Mock(spec=FileInfo, path="README.md"),
        ]
        repo_data.metrics = Mock(
            total_commits=5,
            unique_contributors=1,
            total_files=2,
        )
        repo_data.recent_commits = []
        repo_data.has_ci_config = False
        repo_data.has_readme = True
        repo_data.has_license = False

        # Generate characteristics
        characteristics = generate_repository_characteristics(repo_data)

        # Verify minimal characteristics
        assert characteristics["total_file_count"] == 2
        assert characteristics["max_folder_depth"] == 0
        assert characteristics["language_count"] == 1
        assert characteristics["primary_language"] == "Python"
        assert characteristics["has_javascript_and_typescript"] is False
        assert characteristics["unique_contributors"] == 1
        assert characteristics["refactoring_commit_count"] == 0
        assert characteristics["is_monorepo"] is False
        assert characteristics["is_library"] is False

    def test_unified_ai_includes_characteristics(self):
        """Test that unified AI call includes repository characteristics."""
        # Create report generator
        generator = ReportGenerator()

        # Mock repository data with required attributes
        repo_data = Mock(spec=RepositoryData)
        repo_data.name = "test/repo"
        repo_data.languages = {"Python": 1000}
        repo_data.file_structure = []
        repo_data.metrics = Mock(
            total_commits=10,
            unique_contributors=2,
            total_files=5,
        )
        repo_data.recent_commits = []
        repo_data.size = 100
        repo_data.has_ci_config = False
        repo_data.has_readme = True
        repo_data.has_license = False

        # Test that characteristics are generated
        from src.github_analyzer.core.evidence.repository_characteristics import (
            generate_repository_characteristics,
        )

        characteristics = generate_repository_characteristics(repo_data)

        # Verify basic characteristics
        assert characteristics["total_file_count"] == 0
        assert characteristics["language_count"] == 1
        assert characteristics["primary_language"] == "Python"
        assert characteristics["unique_contributors"] == 2

        # Mock the _generate_unified_insights_and_questions to test integration
        with patch.object(
            generator, "_generate_unified_insights_and_questions"
        ) as mock_generate:
            mock_generate.return_value = {
                "insights": [],
                "questions": [],
                "areas_to_explore": [
                    "Explore Python-only architecture",
                    "Discuss small team collaboration patterns",
                ],
            }

            # Call a method that would use unified generation
            evidence = {"test": "evidence"}
            generator._generate_unified_insights_and_questions(
                evidence=evidence,
                context="startup",
                tier="basic",
                repo_data=repo_data,
                subscription_plan=None,
            )

            # Verify the method was called with repo_data
            mock_generate.assert_called_once_with(
                evidence=evidence,
                context="startup",
                tier="basic",
                repo_data=repo_data,
                subscription_plan=None,
            )

    def test_areas_to_explore_extraction_in_report(self):
        """Test that areas_to_explore are properly extracted in the report."""
        # Mock unified result with areas_to_explore
        unified_result = {
            "insights": [
                {
                    "category": "technical",
                    "title": "Python expertise",
                    "description": "Strong Python skills",
                    "evidence": ["main.py"],
                    "confidence": "high",
                    "impact": "positive",
                }
            ],
            "questions": [],
            "areas_to_explore": [
                "Explore the monorepo architecture decisions",
                "Discuss TypeScript migration strategy",
                "Deep dive into testing philosophy",
            ],
            "analysis_summary": {
                "key_strengths": ["Python expertise"],
                "confidence_explanation": "High confidence",
            },
        }

        # Test extraction logic
        areas = unified_result.get("areas_to_explore", [])
        assert len(areas) == 3
        assert "monorepo architecture" in areas[0]
        assert "TypeScript migration" in areas[1]
        assert "testing philosophy" in areas[2]

        # Test fallback behavior
        unified_result_no_areas = {
            "insights": [],
            "red_flags": ["Some concern"],
        }

        # Should fallback to red_flags
        areas = unified_result_no_areas.get("areas_to_explore", [])
        if not areas:
            areas = unified_result_no_areas.get("red_flags", [])
        assert len(areas) == 1
        assert areas[0] == "Some concern"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
